### ISSUE TITLE
Option for changing or removing '?'

### ISSUE THREAD

**Issue by NaumsJr** [M0dEx/FunQuiz#1]
Hi,

I was just wondering if there is an option for changing the required ? at the beginning of the answer or if there is a way to remove that as a required part of the answer?
If not would it be possible for that to be added?

Thanks,
NaumsJr

**Comment by M0dEx** [comment]
Hey there,

it would be certainly possible for me to include this in the next version as it's not possible in the curret version. As you can see, the plugin is undergoing a recode, so there's no ETA on the release.
Thanks you for reporting this :)

Best regards,
M0dEx.

**Comment by M0dEx** [comment]
The ? before answers was removed for good. I plan on adding the feature of an 'answer prefix' later in the development. Closing for now.
