### ISSUE TITLE
message.yml didn't work

### ISSUE THREAD

**Issue by MineCrocodile** [M0dEx/FunQuiz#3]
any change in message.yml will cause it changed to the original file spontaneously

**Comment by M0dEx** [comment]
I've just tried to copy-paste your messages.yml into mine and ran the plugin - the Chinese messages remained. When you replace the messages, do you reload the plugin or restart the whole server?

**Comment by M0dEx** [comment]
Just tested again, now by reloading the plugin instead of restarting the server and I was able to reproduce the bug. Will investigate now.

**Comment by M0dEx** [comment]
Fixed in the latest commit. Please inform me, whether that fixed the issue.
